export const hosts = {
  INITIALIZE: 'INITIALIZE_HOSTS',
  EXPOSE: 'EXPOSE_HOSTS',
  EXPOSE_INFECT_SUSCEPTIBLE: 'EXPOSE_INFECT_SUSCEPTIBLE_HOSTS',
  EXPOSE_BECOME_INFECTED: 'EXPOSE_BECOME_INFECTED_HOSTS',
  INFECTED_RECOVER_OR_DIE: 'INFECTED_RECOVER_OR_DIE_HOSTS',
};
